// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "63893ac9ad20c540c127eff0c95b82249480d3ae2ce4a1e10e9057e59b64ff72")
